apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
      - name: simple-web-app-pod
        image: 145988340565.dkr.ecr.us-west-2.amazonaws.com/asg:9
        ports: 
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
spec:
  selector:
    app: simple-web-app
  ports:
  - name: http
    protocol: TCP
    port: 9393
    targetPort: 8081
  type: LoadBalancer
